name: Greeting from Mona
on: push
jobs:
  job1:
    name: A
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        run: |
          mkdir run
          cd run
          git clone https://github.com/duhaolong0108/Window.git
          cd window
          ./Main.py