name: Greeting from Mona
on: push
jobs:
  job1:
    name: A
    runs-on: ubuntu-latest
    steps:
      
      - id: Git
        run: git clone https://github.com/duhaolong0108/Window

      - id: Cd
        run: cd Window
      
      - id: Run
        run: python Main.py
