name: Greeting from Mona
on: push
jobs:
  job1:
    name: A
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.10
        run: |
          cd /
          git clone https://github.com/duhaolong0108
          cd window
          ./Main.py